# Launcher.py configuration file.
startPhase: prelaunch
phaseCountlimit: 10
env:
  A: B
prelaunch:
  env:
    A: C
  processList:
  - Name: git pull
    command:
    - git
    - pull
    env:
      A: D
  - Name: pip intall
    command:
    - python
    - "-m"
    - pip
    - install
    - "-r"
    - "./requirements.txt"
    env:
      A: E
  nextPhase: launch
launch:
  env:
    RTI_SERVER_ADDRESS: "localhost"
    RTI_SERVER_PORT: 5000
    RTI_PARTICIPANT_TIMEOUT: 10
    RTI_DEBUG_MODE: false
  runParallel: true
  processList:
  - Name: RTI Server
    command:
    - python
    - RTIAgent.py
    - -server
    env:
      A: G
  - Name: LuluBot
    command:
    - python
    - RTIAgent.py
    env:
      LuluBot: true
  - Name: WebServer
    command:
    - python
    - RTIAgent.py
    - -rtiProcCtrlHost
    env:
      WebServer: true
